//reducer actions
export const ADD_EMPLOYEE_LIST = "ADD_EMPLOYEE_LIST"
export const ADD_TOTAL_RECIEVED = "ADD_TOTAL_RECIEVED"
export const ADD_TOTAL_RECIPIENT = "ADD_TOTAL_RECIPIENT"
export const ADD_PERCENTAGE_DIFF = "ADD_PERCENTAGE_DIFF"
export const ADD_TOTAL_BALANCE = "ADD_TOTAL_BALANCE"
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const CONCAT_EMPLOYEE_LIST = "CONCAT_EMPLOYEE_LIST"