export const BaseUrl = "https://palazo-airtime-core.herokuapp.com"
export const LoginUrl = BaseUrl+"/api/v1/customer/company/login"
export const EmployeeListUrl = BaseUrl+"/api/v1/customer/company/employee_list?id="
export const RegisterUrl = BaseUrl+"/api/v1/customer/company/register"
export const UpdateCompanyProfileUrl = BaseUrl + "/api/v1/customer/company/update"
export const ExportEmployeeAirtimeListUrl = BaseUrl + "/api/v1/customer/company/import_airtime_list"